#!/bin/sh
echo "🔍 Running full lint before push..."
npm run lint
echo "✅ Full lint check passed."

echo "🔍 Running type check..."
npm run type-check
echo "✅ Type check passed."

echo "🔍 Running unit tests..."
npm run test
echo "✅ All tests passed."
